2025-06-17 04:51:57,531 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Tue, 17 Jun 2025 04:51:57 +0000. Up 7.14 seconds.
2025-06-17 04:51:57,531 - main.py[DEBUG]: No kernel command line url found.
2025-06-17 04:51:57,531 - main.py[DEBUG]: Closing stdin.
2025-06-17 04:51:57,532 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2025-06-17 04:51:57,533 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 04:51:57,560 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2025-06-17 04:51:57,561 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-06-17 04:51:57,566 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2025-06-17 04:51:57,567 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-06-17 04:51:57,583 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2025-06-17 04:51:57,584 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-06-17 04:51:57,602 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2025-06-17 04:51:57,603 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-06-17 04:51:57,613 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2025-06-17 04:51:57,613 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 04:51:57,639 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2025-06-17 04:51:57,650 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 04:51:57,667 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2025-06-17 04:51:57,667 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 04:51:57,696 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2025-06-17 04:51:57,697 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 04:51:57,728 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2025-06-17 04:51:57,728 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2025-06-17 04:51:57,739 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2025-06-17 04:51:57,741 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2025-06-17 04:51:57,741 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-06-17 04:51:57,743 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-06-17 04:51:57,744 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-06-17 04:51:57,745 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2025-06-17 04:51:57,745 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2025-06-17 04:51:57,746 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-06-17 04:51:57,747 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-06-17 04:51:57,748 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:57,754 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:57,762 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-06-17 04:51:57,771 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-06-17 04:51:57,771 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-17 04:51:57,771 - stages.py[DEBUG]: no cache found
2025-06-17 04:51:57,771 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-06-17 04:51:57,771 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-17 04:51:57,784 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 04:51:57,784 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-06-17 04:51:57,792 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2025-06-17 04:51:57,792 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2025-06-17 04:51:57,792 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2025-06-17 04:51:57,793 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-06-17 04:51:57,793 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-06-17 04:51:57,793 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-06-17 04:51:57,793 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-06-17 04:51:57,793 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-06-17 04:51:57,793 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-06-17 04:51:57,793 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-06-17 04:51:57,794 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2025-06-17 04:51:57,794 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2025-06-17 04:51:57,794 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2025-06-17 04:51:57,794 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2025-06-17 04:51:57,794 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-06-17 04:51:57,796 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2025-06-17 04:51:57,841 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2025-06-17 04:51:57,841 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2025-06-17 04:51:57,841 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,850 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-06-17 04:51:57,850 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-06-17 04:51:57,850 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,860 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2472b) after 1 attempts
2025-06-17 04:51:57,861 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,870 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 318b) after 1 attempts
2025-06-17 04:51:57,870 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,873 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-06-17 04:51:57,873 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,875 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-06-17 04:51:57,875 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,880 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-06-17 04:51:57,880 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,882 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-06-17 04:51:57,882 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,890 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-06-17 04:51:57,890 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,892 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-06-17 04:51:57,893 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,895 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-06-17 04:51:57,895 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,900 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-06-17 04:51:57,900 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,902 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2025-06-17 04:51:57,903 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,910 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-06-17 04:51:57,910 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,913 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-06-17 04:51:57,913 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,920 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-06-17 04:51:57,920 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,923 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-06-17 04:51:57,923 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,930 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-06-17 04:51:57,930 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,933 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-06-17 04:51:57,933 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,940 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-06-17 04:51:57,940 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,943 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-06-17 04:51:57,943 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,951 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ (200, 230b) after 1 attempts
2025-06-17 04:51:57,951 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,954 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ipv4-associations/ (200, 14b) after 1 attempts
2025-06-17 04:51:57,954 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ipv4-associations/54.202.226.176' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ipv4-associations/54.202.226.176', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,960 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/ipv4-associations/54.202.226.176 (200, 12b) after 1 attempts
2025-06-17 04:51:57,960 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,970 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/device-number (200, 1b) after 1 attempts
2025-06-17 04:51:57,970 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,980 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/interface-id (200, 21b) after 1 attempts
2025-06-17 04:51:57,980 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,990 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/local-hostname (200, 42b) after 1 attempts
2025-06-17 04:51:57,990 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:57,993 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/local-ipv4s (200, 12b) after 1 attempts
2025-06-17 04:51:57,993 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,000 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/mac (200, 17b) after 1 attempts
2025-06-17 04:51:58,000 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,003 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/owner-id (200, 12b) after 1 attempts
2025-06-17 04:51:58,003 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,011 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/public-hostname (200, 50b) after 1 attempts
2025-06-17 04:51:58,011 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,014 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/public-ipv4s (200, 14b) after 1 attempts
2025-06-17 04:51:58,015 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,017 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/security-group-ids (200, 20b) after 1 attempts
2025-06-17 04:51:58,018 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,031 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/security-groups (200, 56b) after 1 attempts
2025-06-17 04:51:58,031 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,034 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/subnet-id (200, 24b) after 1 attempts
2025-06-17 04:51:58,034 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,037 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
2025-06-17 04:51:58,037 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,050 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-id (200, 21b) after 1 attempts
2025-06-17 04:51:58,050 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,053 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-06-17 04:51:58,053 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,060 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:d4:e9:b0:17:4d/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-06-17 04:51:58,060 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,063 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-06-17 04:51:58,063 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,070 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2025-06-17 04:51:58,070 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,073 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-06-17 04:51:58,073 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,080 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2025-06-17 04:51:58,080 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,091 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/ (200, 8b) after 1 attempts
2025-06-17 04:51:58,091 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,100 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key (200, 88b) after 1 attempts
2025-06-17 04:51:58,100 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,110 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-06-17 04:51:58,110 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,113 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-06-17 04:51:58,113 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,120 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-06-17 04:51:58,120 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,123 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-06-17 04:51:58,123 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,130 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-06-17 04:51:58,130 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,133 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-06-17 04:51:58,133 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,140 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 42b) after 1 attempts
2025-06-17 04:51:58,140 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,143 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-06-17 04:51:58,143 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,150 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-06-17 04:51:58,151 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,154 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-06-17 04:51:58,154 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,157 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 9b) after 1 attempts
2025-06-17 04:51:58,157 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,160 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 42b) after 1 attempts
2025-06-17 04:51:58,160 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,170 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 12b) after 1 attempts
2025-06-17 04:51:58,170 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,173 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-06-17 04:51:58,173 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,180 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-06-17 04:51:58,180 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,183 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 50b) after 1 attempts
2025-06-17 04:51:58,183 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,190 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 14b) after 1 attempts
2025-06-17 04:51:58,190 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,193 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-06-17 04:51:58,193 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,200 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2025-06-17 04:51:58,200 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,210 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-06-17 04:51:58,210 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,220 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2025-06-17 04:51:58,220 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,230 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1175b) after 1 attempts
2025-06-17 04:51:58,230 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,233 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2025-06-17 04:51:58,233 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 04:51:58,240 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-06-17 04:51:58,240 - util.py[DEBUG]: Crawl of metadata service took 0.447 seconds
2025-06-17 04:51:58,244 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-06-17 04:51:58,245 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-06-17 04:51:58,246 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-06-17 04:51:58,246 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-06-17 04:51:58,247 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpt896iv15) - w: [600] 12276 bytes/chars
2025-06-17 04:51:58,248 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmp67r05pnd) - w: [644] 8134 bytes/chars
2025-06-17 04:51:58,249 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2025-06-17 04:51:58,249 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2025-06-17 04:51:58,259 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-17 04:51:58,259 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-06-17 04:51:58,259 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,271 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-06-17 04:51:58,272 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-06-17 04:51:58,272 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,273 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-06-17 04:51:58,273 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-06-17 04:51:58,273 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,276 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-17 04:51:58,276 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-17 04:51:58,276 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,291 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-06-17 04:51:58,291 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-06-17 04:51:58,291 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,294 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-17 04:51:58,294 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,294 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 04:51:58,294 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-17 04:51:58,295 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b'
2025-06-17 04:51:58,295 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b (recursive=True)
2025-06-17 04:51:58,301 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/handlers (recursive=False)
2025-06-17 04:51:58,302 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b (recursive=True)
2025-06-17 04:51:58,319 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/scripts (recursive=False)
2025-06-17 04:51:58,321 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b (recursive=True)
2025-06-17 04:51:58,340 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem (recursive=False)
2025-06-17 04:51:58,340 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/datasource (quiet=False)
2025-06-17 04:51:58,341 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/datasource - wb: [644] 29 bytes
2025-06-17 04:51:58,341 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/datasource (recursive=False)
2025-06-17 04:51:58,343 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/datasource (recursive=False)
2025-06-17 04:51:58,343 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2025-06-17 04:51:58,344 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-06-17 04:51:58,345 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-06-17 04:51:58,346 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-06-17 04:51:58,346 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-06-17 04:51:58,346 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-06-17 04:51:58,347 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-06-17 04:51:58,348 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-06-17 04:51:58,349 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-06-17 04:51:58,349 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-06-17 04:51:58,350 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-06-17 04:51:58,350 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-06-17 04:51:58,351 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-06-17 04:51:58,352 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-06-17 04:51:58,353 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12735 bytes
2025-06-17 04:51:58,354 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/obj.pkl (recursive=False)
2025-06-17 04:51:58,355 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/obj.pkl (recursive=False)
2025-06-17 04:51:58,356 - main.py[DEBUG]: [net] init will now be targeting instance id: i-072ecfb7d53bd3c1b. new=True
2025-06-17 04:51:58,356 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-17 04:51:58,356 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-06-17 04:51:58,356 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,378 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-06-17 04:51:58,378 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-06-17 04:51:58,378 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,380 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-06-17 04:51:58,380 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-06-17 04:51:58,380 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,382 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-17 04:51:58,383 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-17 04:51:58,383 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,388 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-06-17 04:51:58,388 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-06-17 04:51:58,388 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,390 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-17 04:51:58,390 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,391 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 04:51:58,392 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-17 04:51:58,392 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-06-17 04:51:58,392 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-06-17 04:51:58,392 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-06-17 04:51:58,392 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-06-17 04:51:58,393 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2025-06-17 04:51:58,393 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-06-17 04:51:58,393 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-06-17 04:51:58,393 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-06-17 04:51:58,393 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2025-06-17 04:51:58,393 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-06-17 04:51:58,393 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2025-06-17 04:51:58,393 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-06-17 04:51:58,393 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2025-06-17 04:51:58,393 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-17 04:51:58,393 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-06-17 04:51:58,394 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2025-06-17 04:51:58,394 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-06-17 04:51:58,394 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2025-06-17 04:51:58,394 - stages.py[DEBUG]: network config disabled by system_cfg
2025-06-17 04:51:58,395 - stages.py[INFO]: network config is disabled by system_cfg
2025-06-17 04:51:58,395 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-06-17 04:51:58,395 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-06-17 04:51:58,395 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/user-data.txt - wb: [600] 2472 bytes
2025-06-17 04:51:58,396 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/user-data.txt (recursive=False)
2025-06-17 04:51:58,397 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/user-data.txt (recursive=False)
2025-06-17 04:51:58,409 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,414 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/user-data.txt.i - wb: [600] 2494 bytes
2025-06-17 04:51:58,415 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/user-data.txt.i (recursive=False)
2025-06-17 04:51:58,416 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/user-data.txt.i (recursive=False)
2025-06-17 04:51:58,417 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data.txt - wb: [600] 0 bytes
2025-06-17 04:51:58,418 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data.txt (recursive=False)
2025-06-17 04:51:58,419 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data.txt (recursive=False)
2025-06-17 04:51:58,421 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data.txt.i - wb: [600] 308 bytes
2025-06-17 04:51:58,422 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data.txt.i (recursive=False)
2025-06-17 04:51:58,423 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data.txt.i (recursive=False)
2025-06-17 04:51:58,424 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data2.txt - wb: [600] 0 bytes
2025-06-17 04:51:58,424 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data2.txt (recursive=False)
2025-06-17 04:51:58,426 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data2.txt (recursive=False)
2025-06-17 04:51:58,427 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data2.txt.i - wb: [600] 308 bytes
2025-06-17 04:51:58,428 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data2.txt.i (recursive=False)
2025-06-17 04:51:58,439 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/vendor-data2.txt.i (recursive=False)
2025-06-17 04:51:58,441 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 04:51:58,442 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-14-20.us-west-2.compute.internal (ip-172-31-14-20)
2025-06-17 04:51:58,442 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-14-20.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:58,678 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-14-20.us-west-2.compute.internal
2025-06-17 04:51:58,678 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-14-20.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:58,684 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpi79dmzp_) - w: [644] 90 bytes/chars
2025-06-17 04:51:58,685 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/consume_data - wb: [644] 25 bytes
2025-06-17 04:51:58,686 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/consume_data (recursive=False)
2025-06-17 04:51:58,688 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/consume_data (recursive=False)
2025-06-17 04:51:58,688 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/consume_data'>)
2025-06-17 04:51:58,689 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-06-17 04:51:58,699 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-06-17 04:51:58,700 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2025-06-17 04:51:58,701 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2025-06-17 04:51:58,701 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,703 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-06-17 04:51:58,703 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2025-06-17 04:51:58,703 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2025-06-17 04:51:58,703 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1823 bytes
2025-06-17 04:51:58,704 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/scripts/user-data.txt (recursive=False)
2025-06-17 04:51:58,705 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/scripts/user-data.txt (recursive=False)
2025-06-17 04:51:58,706 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-06-17 04:51:58,707 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/cloud-config.txt - wb: [600] 154 bytes
2025-06-17 04:51:58,708 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/cloud-config.txt (recursive=False)
2025-06-17 04:51:58,719 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/cloud-config.txt (recursive=False)
2025-06-17 04:51:58,720 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,720 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,720 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,720 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,720 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 04:51:58,720 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-06-17 04:51:58,720 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-06-17 04:51:58,720 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-06-17 04:51:58,721 - stages.py[DEBUG]: no vendordata from datasource
2025-06-17 04:51:58,721 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-06-17 04:51:58,721 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-06-17 04:51:58,721 - stages.py[DEBUG]: no vendordata2 from datasource
2025-06-17 04:51:58,721 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-06-17 04:51:58,721 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-17 04:51:58,721 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-06-17 04:51:58,721 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,743 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-06-17 04:51:58,743 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-06-17 04:51:58,743 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,745 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-06-17 04:51:58,745 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-06-17 04:51:58,745 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,747 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-17 04:51:58,747 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-17 04:51:58,747 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,753 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-06-17 04:51:58,753 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-06-17 04:51:58,753 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,755 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-17 04:51:58,755 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,755 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 04:51:58,755 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-17 04:51:58,756 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-17 04:51:58,756 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,757 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,758 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,889 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-17 04:51:58,890 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-17 04:51:58,890 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-06-17 04:51:58,895 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-06-17 04:51:58,896 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16906 bytes
2025-06-17 04:51:58,910 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/obj.pkl (recursive=False)
2025-06-17 04:51:58,911 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/obj.pkl (recursive=False)
2025-06-17 04:51:58,912 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-06-17 04:51:58,912 - main.py[DEBUG]: no di_report found in config.
2025-06-17 04:51:58,914 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,914 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,918 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,918 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,921 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,922 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,929 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,930 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,933 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,933 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,937 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,938 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,949 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,949 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,956 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,956 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,960 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,960 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,965 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,965 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,969 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,969 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,979 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,979 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,983 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,983 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:58,987 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:58,987 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:59,000 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:59,000 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:59,005 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:51:59,005 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:51:59,008 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 04:51:59,009 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2025-06-17 04:51:59,009 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2025-06-17 04:51:59,009 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f50817ec6a0>)
2025-06-17 04:51:59,010 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2025-06-17 04:51:59,010 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2025-06-17 04:51:59,010 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-06-17 04:51:59,010 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-06-17 04:51:59,010 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_seed_random - wb: [644] 24 bytes
2025-06-17 04:51:59,011 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_seed_random (recursive=False)
2025-06-17 04:51:59,012 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_seed_random (recursive=False)
2025-06-17 04:51:59,013 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_seed_random'>)
2025-06-17 04:51:59,013 - cc_seed_random.py[DEBUG]: no command provided
2025-06-17 04:51:59,013 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2025-06-17 04:51:59,013 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2025-06-17 04:51:59,014 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2025-06-17 04:51:59,014 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f50817ec6a0>)
2025-06-17 04:51:59,014 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2025-06-17 04:51:59,014 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2025-06-17 04:51:59,014 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-06-17 04:51:59,014 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2025-06-17 04:51:59,014 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_files - wb: [644] 24 bytes
2025-06-17 04:51:59,015 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_files (recursive=False)
2025-06-17 04:51:59,016 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_files (recursive=False)
2025-06-17 04:51:59,017 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_files'>)
2025-06-17 04:51:59,017 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2025-06-17 04:51:59,017 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2025-06-17 04:51:59,017 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2025-06-17 04:51:59,018 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2025-06-17 04:51:59,018 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_metadata - wb: [644] 25 bytes
2025-06-17 04:51:59,018 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_metadata (recursive=False)
2025-06-17 04:51:59,030 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_metadata (recursive=False)
2025-06-17 04:51:59,031 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_write_metadata'>)
2025-06-17 04:51:59,031 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2025-06-17 04:51:59,035 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-06-17 04:51:59,036 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-06-17 04:51:59,036 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2025-06-17 04:51:59,037 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2025-06-17 04:51:59,037 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-06-17 04:51:59,038 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-06-17 04:51:59,038 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2025-06-17 04:51:59,039 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2025-06-17 04:51:59,039 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-06-17 04:51:59,039 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-06-17 04:51:59,039 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f50817ec940>)
2025-06-17 04:51:59,039 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-06-17 04:51:59,039 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,070 - util.py[DEBUG]: Reading from /proc/1522/mountinfo (quiet=False)
2025-06-17 04:51:59,070 - util.py[DEBUG]: Read 2927 bytes from /proc/1522/mountinfo
2025-06-17 04:51:59,071 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-06-17 04:51:59,071 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-06-17 04:51:59,071 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-06-17 04:51:59,071 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-06-17 04:51:59,072 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,213 - util.py[DEBUG]: resize_devices took 0.143 seconds
2025-06-17 04:51:59,213 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-06-17 04:51:59,214 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2025-06-17 04:51:59,214 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-06-17 04:51:59,214 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-06-17 04:51:59,214 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f50817ec6a0>)
2025-06-17 04:51:59,214 - util.py[DEBUG]: Reading from /proc/1522/mountinfo (quiet=False)
2025-06-17 04:51:59,215 - util.py[DEBUG]: Read 2927 bytes from /proc/1522/mountinfo
2025-06-17 04:51:59,215 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2025-06-17 04:51:59,215 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2025-06-17 04:51:59,216 - util.py[DEBUG]: Forked child 1660 who will run callback log_time
2025-06-17 04:51:59,217 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2025-06-17 04:51:59,217 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,217 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2025-06-17 04:51:59,217 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2025-06-17 04:51:59,218 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2025-06-17 04:51:59,218 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_disk_setup - wb: [644] 25 bytes
2025-06-17 04:51:59,230 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_disk_setup (recursive=False)
2025-06-17 04:51:59,232 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_disk_setup (recursive=False)
2025-06-17 04:51:59,233 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_disk_setup'>)
2025-06-17 04:51:59,233 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2025-06-17 04:51:59,233 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-06-17 04:51:59,234 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-06-17 04:51:59,234 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_mounts - wb: [644] 25 bytes
2025-06-17 04:51:59,235 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_mounts (recursive=False)
2025-06-17 04:51:59,236 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_mounts (recursive=False)
2025-06-17 04:51:59,237 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_mounts'>)
2025-06-17 04:51:59,237 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-06-17 04:51:59,237 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-06-17 04:51:59,238 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-06-17 04:51:59,238 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-06-17 04:51:59,238 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: changed default device swap => None
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: no need to setup swap
2025-06-17 04:51:59,238 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-06-17 04:51:59,238 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2025-06-17 04:51:59,238 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2025-06-17 04:51:59,239 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2025-06-17 04:51:59,239 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f50817ec940>)
2025-06-17 04:51:59,249 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-06-17 04:51:59,249 - util.py[DEBUG]: Read 90 bytes from /var/lib/cloud/data/set-hostname
2025-06-17 04:51:59,249 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2025-06-17 04:51:59,250 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2025-06-17 04:51:59,250 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-06-17 04:51:59,250 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-06-17 04:51:59,250 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f50817eca00>)
2025-06-17 04:51:59,250 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-14-20.us-west-2.compute.internal (ip-172-31-14-20)
2025-06-17 04:51:59,250 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,259 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-14-20.us-west-2.compute.internal in 1 files
2025-06-17 04:51:59,260 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 42 bytes
2025-06-17 04:51:59,261 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-06-17 04:51:59,263 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-06-17 04:51:59,263 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2025-06-17 04:51:59,264 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2025-06-17 04:51:59,264 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2025-06-17 04:51:59,264 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f50817ec940>)
2025-06-17 04:51:59,264 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2025-06-17 04:51:59,264 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2025-06-17 04:51:59,264 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2025-06-17 04:51:59,265 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2025-06-17 04:51:59,265 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ca_certs - wb: [644] 25 bytes
2025-06-17 04:51:59,266 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ca_certs (recursive=False)
2025-06-17 04:51:59,267 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ca_certs (recursive=False)
2025-06-17 04:51:59,267 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ca_certs'>)
2025-06-17 04:51:59,268 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2025-06-17 04:51:59,268 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2025-06-17 04:51:59,268 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2025-06-17 04:51:59,268 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2025-06-17 04:51:59,268 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_rsyslog - wb: [644] 25 bytes
2025-06-17 04:51:59,279 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_rsyslog (recursive=False)
2025-06-17 04:51:59,281 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_rsyslog (recursive=False)
2025-06-17 04:51:59,281 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_rsyslog'>)
2025-06-17 04:51:59,282 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2025-06-17 04:51:59,282 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2025-06-17 04:51:59,282 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2025-06-17 04:51:59,282 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2025-06-17 04:51:59,282 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_selinux - wb: [644] 25 bytes
2025-06-17 04:51:59,283 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_selinux (recursive=False)
2025-06-17 04:51:59,283 - util.py[DEBUG]: backgrounded Resizing took 0.066 seconds
2025-06-17 04:51:59,285 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_selinux (recursive=False)
2025-06-17 04:51:59,285 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_selinux'>)
2025-06-17 04:51:59,303 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2025-06-17 04:51:59,303 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2025-06-17 04:51:59,303 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2025-06-17 04:51:59,303 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2025-06-17 04:51:59,303 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2025-06-17 04:51:59,303 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2025-06-17 04:51:59,303 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-06-17 04:51:59,304 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2025-06-17 04:51:59,304 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_users_groups - wb: [644] 25 bytes
2025-06-17 04:51:59,305 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_users_groups (recursive=False)
2025-06-17 04:51:59,307 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_users_groups (recursive=False)
2025-06-17 04:51:59,308 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_users_groups'>)
2025-06-17 04:51:59,308 - __init__.py[INFO]: User ec2-user already exists, skipping.
2025-06-17 04:51:59,309 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,396 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-06-17 04:51:59,405 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2025-06-17 04:51:59,407 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2025-06-17 04:51:59,408 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2025-06-17 04:51:59,409 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2025-06-17 04:51:59,410 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2025-06-17 04:51:59,410 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-06-17 04:51:59,410 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-06-17 04:51:59,410 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ssh - wb: [644] 25 bytes
2025-06-17 04:51:59,411 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ssh (recursive=False)
2025-06-17 04:51:59,413 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ssh (recursive=False)
2025-06-17 04:51:59,413 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ssh'>)
2025-06-17 04:51:59,414 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,442 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-06-17 04:51:59,472 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:51:59,493 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-06-17 04:51:59,512 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-06-17 04:51:59,512 - util.py[DEBUG]: Read 129 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-06-17 04:51:59,512 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-06-17 04:51:59,512 - util.py[DEBUG]: Read 209 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-06-17 04:51:59,513 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 04:51:59,514 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-06-17 04:51:59,515 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2025-06-17 04:51:59,516 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2025-06-17 04:51:59,516 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-17 04:51:59,517 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,517 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,517 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2025-06-17 04:51:59,517 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-06-17 04:51:59,517 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2025-06-17 04:51:59,517 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 88 bytes
2025-06-17 04:51:59,518 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,518 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,518 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-06-17 04:51:59,520 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 04:51:59,520 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-06-17 04:51:59,521 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-06-17 04:51:59,523 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-17 04:51:59,523 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,523 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,524 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-06-17 04:51:59,524 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-06-17 04:51:59,524 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2025-06-17 04:51:59,524 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 254 bytes
2025-06-17 04:51:59,524 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,524 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 04:51:59,525 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-06-17 04:51:59,526 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2025-06-17 04:51:59,527 - main.py[DEBUG]: Ran 17 modules with 0 failures
2025-06-17 04:51:59,527 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpg1n9k_m2) - w: [644] 486 bytes/chars
2025-06-17 04:51:59,527 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 04:51:59,528 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-06-17 04:51:59,528 - util.py[DEBUG]: cloud-init mode 'init' took 2.163 seconds (2.16)
2025-06-17 04:51:59,528 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-06-17 04:52:00,592 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Tue, 17 Jun 2025 04:52:00 +0000. Up 10.14 seconds.
2025-06-17 04:52:00,602 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,603 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,606 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,607 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,620 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,620 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,629 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,630 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,633 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,633 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,639 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,640 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,643 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,643 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,649 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,649 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,659 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,659 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,662 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:00,663 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:00,665 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 04:52:00,665 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2025-06-17 04:52:00,666 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2025-06-17 04:52:00,666 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2025-06-17 04:52:00,666 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_keyboard - wb: [644] 25 bytes
2025-06-17 04:52:00,679 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_keyboard (recursive=False)
2025-06-17 04:52:00,683 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_keyboard (recursive=False)
2025-06-17 04:52:00,683 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_keyboard'>)
2025-06-17 04:52:00,683 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2025-06-17 04:52:00,684 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2025-06-17 04:52:00,684 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-06-17 04:52:00,684 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-06-17 04:52:00,684 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_locale - wb: [644] 25 bytes
2025-06-17 04:52:00,685 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_locale (recursive=False)
2025-06-17 04:52:00,686 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_locale (recursive=False)
2025-06-17 04:52:00,687 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_locale'>)
2025-06-17 04:52:00,687 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-06-17 04:52:00,687 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-06-17 04:52:00,687 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-06-17 04:52:00,687 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-06-17 04:52:00,687 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-06-17 04:52:00,688 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2025-06-17 04:52:00,701 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-06-17 04:52:00,704 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-06-17 04:52:00,705 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2025-06-17 04:52:00,705 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-06-17 04:52:00,705 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2025-06-17 04:52:00,706 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_set_passwords - wb: [644] 24 bytes
2025-06-17 04:52:00,706 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_set_passwords (recursive=False)
2025-06-17 04:52:00,708 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_set_passwords (recursive=False)
2025-06-17 04:52:00,708 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_set_passwords'>)
2025-06-17 04:52:00,708 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 04:52:00,761 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 04:52:00,761 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-06-17 04:52:00,761 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2025-06-17 04:52:00,762 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2025-06-17 04:52:00,762 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2025-06-17 04:52:00,762 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2025-06-17 04:52:00,762 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2025-06-17 04:52:00,763 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_variables - wb: [644] 23 bytes
2025-06-17 04:52:00,764 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_variables (recursive=False)
2025-06-17 04:52:00,765 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_variables (recursive=False)
2025-06-17 04:52:00,766 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_variables'>)
2025-06-17 04:52:00,766 - cc_yum_variables.py[INFO]: handling yum-variables
2025-06-17 04:52:00,766 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.7, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2025-06-17 04:52:00,766 - cc_yum_variables.py[INFO]: No yum vars to delete
2025-06-17 04:52:00,766 - cc_yum_variables.py[INFO]: No yum vars to set
2025-06-17 04:52:00,766 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2025-06-17 04:52:00,766 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2025-06-17 04:52:00,767 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2025-06-17 04:52:00,767 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_add_repo - wb: [644] 24 bytes
2025-06-17 04:52:00,768 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_add_repo (recursive=False)
2025-06-17 04:52:00,769 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_add_repo (recursive=False)
2025-06-17 04:52:00,779 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_yum_add_repo'>)
2025-06-17 04:52:00,780 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2025-06-17 04:52:00,780 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2025-06-17 04:52:00,780 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2025-06-17 04:52:00,780 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2025-06-17 04:52:00,780 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ntp - wb: [644] 24 bytes
2025-06-17 04:52:00,781 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ntp (recursive=False)
2025-06-17 04:52:00,782 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ntp (recursive=False)
2025-06-17 04:52:00,783 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_ntp'>)
2025-06-17 04:52:00,783 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2025-06-17 04:52:00,783 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2025-06-17 04:52:00,783 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-06-17 04:52:00,783 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-06-17 04:52:00,784 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_timezone - wb: [644] 25 bytes
2025-06-17 04:52:00,784 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_timezone (recursive=False)
2025-06-17 04:52:00,786 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_timezone (recursive=False)
2025-06-17 04:52:00,786 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_timezone'>)
2025-06-17 04:52:00,786 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2025-06-17 04:52:00,786 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2025-06-17 04:52:00,786 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2025-06-17 04:52:00,787 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2025-06-17 04:52:00,787 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f4202835700>)
2025-06-17 04:52:00,787 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2025-06-17 04:52:00,787 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2025-06-17 04:52:00,787 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2025-06-17 04:52:00,787 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2025-06-17 04:52:00,787 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_runcmd - wb: [644] 24 bytes
2025-06-17 04:52:00,788 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_runcmd (recursive=False)
2025-06-17 04:52:00,789 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_runcmd (recursive=False)
2025-06-17 04:52:00,790 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-072ecfb7d53bd3c1b/sem/config_runcmd'>)
2025-06-17 04:52:00,790 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2025-06-17 04:52:00,790 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2025-06-17 04:52:00,790 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-06-17 04:52:00,791 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp8xny68za) - w: [644] 513 bytes/chars
2025-06-17 04:52:00,791 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 04:52:00,791 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2025-06-17 04:52:00,791 - util.py[DEBUG]: cloud-init mode 'modules' took 0.380 seconds (0.38)
2025-06-17 04:52:00,791 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-06-17 04:52:01,626 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Tue, 17 Jun 2025 04:52:01 +0000. Up 11.16 seconds.
2025-06-17 04:52:01,631 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 04:52:01,632 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 04:52:01,640 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 04:52:01,641 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2025-06-17 04:52:01,642 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2025-06-17 04:52:01,642 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7fdf9f3c70a0>)
2025-06-17 04:52:01,642 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2025-06-17 04:52:17,469 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2025-06-17 04:52:17,469 - main.py[DEBUG]: Ran 1 modules with 0 failures
2025-06-17 04:52:17,470 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmprfxlqv7z) - w: [644] 541 bytes/chars
2025-06-17 04:52:17,471 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp9da2jde5) - w: [644] 64 bytes/chars
2025-06-17 04:52:17,471 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-06-17 04:52:17,471 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 04:52:17,471 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2025-06-17 04:52:17,471 - util.py[DEBUG]: cloud-init mode 'modules' took 16.018 seconds (13.92)
2025-06-17 04:52:17,471 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
